# Generated by Django 5.0 on 2024-02-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_orderitems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='menu',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='menu',
            field=models.ManyToManyField(related_name='products', to='restaurant.menu'),
        ),
    ]
