# Generated by Django 5.0 on 2024-07-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_menu_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='user',
        ),
    ]
