# Generated by Django 5.0 on 2024-07-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_menu_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='used_in_order',
            field=models.BooleanField(default=False),
        ),
    ]
