# Generated by Django 5.0 on 2024-07-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menu_used_in_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='used_in_order',
        ),
    ]
