# Generated by Django 5.0 on 2024-02-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
