# Generated by Django 5.0 on 2024-03-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_review_image_review_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('message_date',)},
        ),
    ]
